version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: q1w2e3r4

    ports:
      - 3360:3306

    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:  
